version: '3.8'

networks:
  bank-network:
    driver: bridge

services:
  postgres:
    image: postgres:13
    container_name: bank-postgres  # Измененное имя
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sede343343
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: bank-redis  # Измененное имя
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: bank-elasticsearch  # Измененное имя
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.ml.enabled=false
      - ingest.geoip.downloader.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  app:
    build: .
    container_name: bank-app  # Измененное имя
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://bank-postgres:5432/demo  # Обновленный хост
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sede343343
      SPRING_REDIS_HOST: bank-redis  # Обновленный хост
      SPRING_ELASTICSEARCH_URIS: http://bank-elasticsearch:9200  # Обновленный хост
    ports:
      - "8081:8081"

volumes:
  postgres-data:
  redis-data:
  elasticsearch-data: